before_install:
- 'mkdir -p ~/.pebble-sdk'
- 'touch ~/.pebble-sdk/ENABLE_ANALYTICS'
- "curl -L https://s3.amazonaws.com/assets.getpebble.com/pebble-tool/pebble-sdk-4.5-linux64.tar.bz2 | tar -xjC /tmp"
- "export T_PEBBLE_SDK_PATH=/tmp/pebbl*/bin"
- 'export PATH=${PATH}:${T_PEBBLE_SDK_PATH}'
- 'virtualenv --no-site-packages "${T_PEBBLE_SDK_PATH}"/.env'
- 'source "${T_PEBBLE_SDK_PATH}"/.env/bin/activate'
- 'pipe install -r "${T_PEBBLE_SDK_PATH}"/requirements.txt'
- deactivate
- 'yes | pebble sdk install "$(pebble sdk list | grep -e "^[[:digit:]]" | head -n 1)"'
language: node_js
script:
- npm test
- pebble build
after_success: 
- "if git describe --exact-match; then openssl aes-256-cbc -K $encrypted_edbbfc730e8b_key -iv $encrypted_edbbfc730e8b_iv -in deploy.npmrc.enc -out ~/.npmrc -d && pebble package publish; else : fi"
