# Copyright (C) 2016 Nathan Phillip Brink
# Distributed under the terms of the MIT license, see LICENSE.md.
before_install:
- sudo apt-get install python-virtualenv valgrind
- 'mkdir -p ~/.pebble-sdk'
- 'touch ~/.pebble-sdk/ENABLE_ANALYTICS'
- "curl -L https://s3.amazonaws.com/assets.getpebble.com/pebble-tool/pebble-sdk-4.5-linux64.tar.bz2 | tar -xjC /tmp"
- "for T_PEBBLE_SDK_ROOT in /tmp/pebbl*; do :; done"
- 'export PATH=${PATH}:${T_PEBBLE_SDK_ROOT}/bin'
- 'virtualenv --no-site-packages "${T_PEBBLE_SDK_ROOT}"/.env'
- 'source "${T_PEBBLE_SDK_ROOT}"/.env/bin/activate'
- 'pip install -r "${T_PEBBLE_SDK_ROOT}"/requirements.txt'
- deactivate
- 'yes | pebble sdk install "$(pebble sdk list | grep -e "^[[:digit:]]" | head -n 1)"'
language: node_js
node_js:
- "6"
script:
- CC=c99 npm test
- pebble build
after_success:
# Using “npm config get userconfig” because ~/.npmrc is probably not the one being used by nvm.
- 'if git describe --exact-match; then openssl aes-256-cbc -K $encrypted_edbbfc730e8b_key -iv $encrypted_edbbfc730e8b_iv -in deploy.npmrc.enc -d >> "$(npm config get userconfig)" && pebble package publish; fi'
